debug: 1                    # Range 0-4 (0 means no debug statements will print)

device: /dev/ttyUSB0
frame_id: gps #TODO: change it in the future
config_on_startup: false	#DO NOT CHANGE OTHERWISE IT OVERWRITES THE MODULE CONFIGURATION
uart1:
  baudrate: 38400
rate: 1
nav_rate: 1
publish:
  all: true
