ekf_se_map:
  frequency: 4
  two_d_mode: true
  print_diagnostics: true
  publish_tf: true

  map_frame: map
  odom_frame: odom
  base_link_frame: base_link
  world_frame: odom

  odom0: odometry/gps
  odom0_config: [true,  true,  false,
                false, false, false,
                false, false, false,
                false, false, false,
                false, false, false]

  imu0: gps/navheading
  imu0_config: [false, false, false,
                false,  false,  true,
                false, false, false,
                false,  false,  false,
                false,  false,  false]
  imu0_nodelay: false
  imu0_differential: false
  imu0_relative: true
  imu0_queue_size: 5
